# Generated by Django 4.2.1 on 2024-09-06 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='A unique username with a minimum length of 7 characters.', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('password', models.CharField(help_text='A secure password with a maximum length of 35 characters.', max_length=35)),
                ('email', models.EmailField(help_text='A valid email address.', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('account_type', models.IntegerField(choices=[(1, 'Player'), (2, 'Research')], help_text='The type of user account: Player or Research.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
