# Generated by Django 4.2.1 on 2024-09-06 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoeuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='tictactoeuser',
            name='username',
            field=models.CharField(help_text='A unique username with a minimum length of 7 characters.', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
