# Generated by Django 4.2.1 on 2024-09-06 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_app', '0002_alter_tictactoeuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoeuser',
            name='age',
            field=models.IntegerField(default=18, help_text='The age of the user.', validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='tictactoeuser',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='A securely hashed API key for the user.', max_length=128),
        ),
        migrations.AddField(
            model_name='tictactoeuser',
            name='profile_name',
            field=models.CharField(default=models.CharField(help_text='A unique username with a minimum length of 5 characters.', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)]), help_text="A display name for the user's profile.", max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tictactoeuser',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Player'), (2, 'Research')], default=1, help_text='The type of user account: Player or Research.'),
        ),
        migrations.AlterField(
            model_name='tictactoeuser',
            name='email',
            field=models.EmailField(help_text='A valid email address.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='tictactoeuser',
            name='username',
            field=models.CharField(help_text='A unique username with a minimum length of 5 characters.', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
