# Generated by Django 4.2.1 on 2024-09-06 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_app', '0003_tictactoeuser_age_tictactoeuser_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoeuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tictactoeuser',
            name='verification_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tictactoeuser',
            name='age',
            field=models.IntegerField(help_text='The age of the user.', validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='tictactoeuser',
            name='profile_name',
            field=models.CharField(help_text="A display name for the user's profile.", max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
