# Generated by Django 4.2.1 on 2024-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_app', '0007_game_gamelog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamelog',
            index=models.Index(fields=['game', 'turn_number'], name='tictactoe_a_game_id_082087_idx'),
        ),
    ]
