# Generated by Django 4.2.1 on 2024-09-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_app', '0008_gamelog_tictactoe_a_game_id_082087_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tictactoeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
