# Generated by Django 4.2.1 on 2024-09-06 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_app', '0005_rename_is_email_verified_tictactoeuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoeuser',
            name='age',
            field=models.IntegerField(help_text='The age of the user. Must be between 13 and 120 years.', validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
