name: CD Pipeline to Google Cloud VM

on:
  push:
    branches:
      - main
      - game/api_integration

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      # Docker image names
      FRONTEND_IMAGE: "tictactoe/frontend:latest"
      BACKEND_IMAGE: "tictactoe/backend:latest"
      DOCKER_COMPOSE_FILE: "docker-compose.prod.yml"

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to DockerHub (optional)
      - name: Log in to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker images for frontend and backend
      - name: Build frontend Docker image
        run: |
          docker build -t $FRONTEND_IMAGE ./tictactoe_project/tictactoe_frontend/tic-tac-toe-frontend
          docker save $FRONTEND_IMAGE > frontend.tar
        shell: bash

      - name: Build backend Docker image
        run: |
          docker build -t $BACKEND_IMAGE ./tictactoe_project
          docker save $BACKEND_IMAGE > backend.tar
        shell: bash

      # Step 5: Copy Docker images and Compose file to VM
      - name: Copy files to VM
        env:
          GCP_VM_IP: ${{ vars.GCP_VM_IP }}
        run: |
          scp -o StrictHostKeyChecking=no -i "$HOME/.ssh/deploy_key" frontend.tar ${{ vars.GCP_USERNAME }}@$GCP_VM_IP:/home/${{ vars.GCP_USERNAME }}/
          scp -o StrictHostKeyChecking=no -i "$HOME/.ssh/deploy_key" backend.tar ${{ vars.GCP_USERNAME }}@$GCP_VM_IP:/home/${{ vars.GCP_USERNAME }}/
          scp -o StrictHostKeyChecking=no -i "$HOME/.ssh/deploy_key" $DOCKER_COMPOSE_FILE ${{ vars.GCP_USERNAME }}@$GCP_VM_IP:/home/${{ vars.GCP_USERNAME }}/

      # Step 6: SSH into VM and deploy with Docker Compose
      - name: Deploy on VM
        env:
          GCP_VM_IP: ${{ vars.GCP_VM_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i "$HOME/.ssh/deploy_key" ${{ vars.GCP_USERNAME }}@$GCP_VM_IP << EOF
            cd /home/${{ vars.GCP_USERNAME }}
            docker load < frontend.tar
            docker load < backend.tar
            docker-compose -f $DOCKER_COMPOSE_FILE up -d --build
          EOF