name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Setup
  setup:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12 environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          mkdir -p "$(dirname "$HOME/google-cloud-key.json")"
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > "$HOME/google-cloud-key.json"
      
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2.2.2

  # Job 2: Backend Tests
  backend_tests:
    runs-on: ubuntu-latest
    needs: setup
    environment: development
    env:
      GOOGLE_APPLICATION_CREDENTIALS: "$HOME/google-cloud-key.json"
      ENC_SECRET_KEY: ${{ secrets.ENC_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Backend Dependencies
        run: |
          cd tictactoe_project
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        run: |
          cd tictactoe_project
          source venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Backend Unit Tests
        run: |
          cd tictactoe_project
          source venv/bin/activate
          python manage.py test

  # Job 3: Frontend Tests
  frontend_tests:
    runs-on: ubuntu-latest
    needs: setup
    environment: development
    env:
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
      REACT_APP_ENV: ${{ vars.REACT_APP_ENV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Frontend Dependencies
        run: |
          cd tictactoe_project/tictactoe_frontend/tic-tac-toe-frontend
          npm install

      # Optional: Add frontend-specific tests if available

  # Job 4: Integration Tests
  integration_tests:
    runs-on: ubuntu-latest
    needs: [backend_tests, frontend_tests]
    environment: development
    env:
      ENC_SECRET_KEY: ${{ secrets.ENC_SECRET_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: "$HOME/google-cloud-key.json"
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
      REACT_APP_ENV: ${{ vars.REACT_APP_ENV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Backend Server
        run: |
          cd tictactoe_project
          source venv/bin/activate
          nohup python manage.py runserver 0.0.0.0:8000 --noreload &
          sleep 15  # Allow server to start
          curl http://localhost:8000/api/swagger/  # Verify server is running

      - name: Start Frontend Server
        run: |
          cd tictactoe_project/tictactoe_frontend/tic-tac-toe-frontend
          nohup npm start &
          sleep 10  # Allow frontend to start
          curl http://localhost:3000/login/  # Verify frontend server is running

      - name: Run Selenium Tests
        run: |
          cd tictactoe_project
          source venv/bin/activate
          pytest

  # Job 5: Cleanup
  cleanup:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Stop Backend Server
        run: |
          pkill -f "python manage.py runserver"

      - name: Stop Frontend Server
        run: |
          pkill -f "npm start"